services:
    mongodb:
        image: mongo
        container_name: mongodb
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: dar
            MONGO_INITDB_ROOT_PASSWORD: dar
            MONGO_INITDB_DATABASE: shelter
        volumes:
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js